site_name: UCB EECS Exam Generator

repo_name: rohit507/exam_gen

nav:
  - Home: index.md
  - Tutorial: # tutorial/*
    - Your First Assignment: tutorial/first_assignment.md
    - Classrooms and Rosters: tutorial/classrooms_and_rosters.md
    - Writing Questions: tutorial/writing_questions.md
    - Customization and Randomization: tutorial/customization_and_randomization.md
    - Advanced Template Use: tutorial/advanced_template_use.md
    - Multi-Part Questions: tutorial/multi_part_questions.md
    - Project Organization: tutorial/project_organization.md
    - External and Generated Assets: tutorial/external_and_generated_assets.md
    - Multiple Choice Questions: # tutorial/multiple_choice
      - Simple Questions: tutorial/multiple_choice/simple_question.md
      - Choices and Shuffling: tutorial/multiple_choice/choices_and_shuffling.md
      - Custom Grading and Setup: tutorial/multiple_choice/custom_grading_and_setup.md
    - Answers and Scoring: tutorial/answers_and_scoring.md
    # - Bulk Operations:
  - User's Guide: # user_guide/*
    - Project Setup and Organization: user_guide/project_setup.md
    - "Exams/Assignments": user_guide/exams.md
    # - External Assets: user_guide/
      # - Specifying Static Assets: user_guide/
      # - Creating Dynamic Assets: user_guide/
      # - File Search and Lookup: user_guide/
    # - Internal Processing: user_guide/
    # - Questions: user_guide/
      # - Basic Questions: user_guide/
      # - Nesting: user_guide/
      # - Multiple Choice: user_guide/
    # - Templates: user_guide/
      # - Template Formatting: user_guide/
      # - Template Variables: user_guide/
      # - Class Level Templates: user_guide/
      # - Debug Information: user_guide/
      # - Template Search and Lookup: user_guide/
    # - Classrooms and Student Data:
      # - Classrooms:
      # - Rosters:
      # - Answers:
      # - Scores:
      # - Grades:
    # - User Setup: user_guide/
      # - Randomness: user_guide/
      # - Template Context: user_guide/
    # - Command Line Options: user_guide/
      # - Parse Roster: user_guide/
      # - Build Exam: user_guide/
      # - Build Solutions: user_guide/
    # - Output Formats: user_guide/
      # - Latex: user_guide/
    # - Exam Administration: user_guide/ # exam_admin/*
      # - Distributing Exams: user_guide/
      # - Canvas / BCourses : user_guide/ exam_admin/canvas.md
      # - Manual Scoring: user_guide/
      # - Getting Grades: user_guide/
  # - Developer Guide: # dev_guide/*
    # - Development Environment Setup: dev_guide/dev_env_setup.md
    # - Development Workflow: dev_guide/development_workflow.md
    # - Project Organization: dev_guide/project_organization.md
    # - Build Process: dev_guide/build_phases.md
    # - Adding Components: # dev_guide/adding_components/*
      # - Roster Parsers:
      # - Answer Parsers:
      # - Score Parsers:
      # - Grade Printers:
      # - Question Types:
      # - Output Formats:
      # - Templates:
    # - Adding Properties:
      # - User Setup Arguments:
      # - Configuration Variables:
      # - Template Variables:
    # - Adding Question Types:
      # - Basic Changes:
      # - Answer Formats:
      # - Auto-grading:
      # - Templates:
    # - Documentation and gh-pages:
  # - API Documentation: # api/*
  #   # - Summary: api/Summary.md
  #   - exam_gen.build: # api/build/*
  #     - .build.cli: api/build/cli.md
  #     - .build.data: api/build/data.md
  #     - .build.formats: api/build/formats.md
  #   - exam_gen.classrooom: # api/classroom/*
  #     - .classroom.answers: api/classroom/answers.md
  #     - .classroom.base: api/classroom/base.md
  #     - .classroom.grades: api/classroom/grade.md
  #     - .classroom.rosters: api/classroom/rosters.md
  #     - .classroom.scores: api/classroom/scores.md
  #     - .classroom.student: api/classroom/student.md
  #   - exam_gen.exam : api/exam.md
  #   - exam_gen.property: # api/property/*
  #     - .property.answerable : api/property/answerable.md
  #     - .property.auto_gradeable : api/property/auto_gradeable.md
  #     - .property.buildable : api/property/buildable.md
  #     - .property.document : api/property/document.md
  #     - .property.format : api/property/format.md
  #     - .property.gradeable : api/property/gradeable.md
  #     - .property.has_context : api/property/has_context.md
  #     - .property.has_dir_path : api/property/has_dir_path.md
  #     - .property.has_metadata : api/property/has_metadata.md
  #     - .property.has_rng : api/property/has_rng.md
  #     - .property.has_settings : api/property/has_settings.md
  #     - .property.has_user_setup : api/property/has_user_setup.md
  #     - .property.numbered : api/property/numbered.md
  #     - .property.personalized : api/property/personalized.md
  #     - .property.templated : api/property/templated.md
  #   # - exam_gen.question: # api/question/*
  #     # - .question.base: api/question/base.md
  #     # - .question.multiple_choice: api/question/multiple_choice.md
  #   - exam_gen.util: # api/util/*
  #     # - .util.config : api/util/config.md
  #     # - .util.excel_cols : api/util/excel_cols.md
  #     # - .util.file_ops : api/util/file_ops.md
  #     # - .util.logging : api/util/logging.md
  #     # - .util.merge_dict : api/util/merge_dict.md
  #     # - .util.prepare_attrs : api/util/prepare_attrs.md
  #     # - .util.stable_hash : api/util/stable_hash.md
  #     - .util.selectors : api/util/selectors.md
  #     # - .util.user_setup : api/util/user_setup.md
  #     # - .util.versioned_option : api/util/versioned_option.md
  #     # - .util.with_options : api/util/with_options.md
  - Quick Reference: quick_reference.md

plugins:
  - search
  - macros:
      module_name: docs
      j2_block_start_string: '[|%'
      j2_block_end_string: '%|]'
      j2_variable_start_string: '[|'
      j2_variable_end_string: '|]'

  - localsearch
  - mkdocstrings:
      handlers:
        python:
          # selection:
          #   inherited_members: True
          rendering:
            show_source: True
            show_if_no_docstring: True
      watch:
        - exam_gen/

markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - toc:
      permalink: true

use_directory_urls: false

theme:
  name: material
  custom_dir : docs/theme/
  palette:
    scheme: slate
    primary: blue
    secondary: yellow
  icon:
    repo: check-square
