site_name: UCB EECS Exam Generator

repo_name: rohit507/exam_gen

theme:
  name: material
  custom_dir : docs/theme/
  palette:
    scheme: slate
    primary: blue
    secondary: yellow
  icon:
    repo: check-square

plugins:
  - search
  - localsearch
  - mkdocstrings:
      watch:
        - exam_gen/ 

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

use_directory_urls: false
