site_name: UCB EECS Exam Generator

repo_name: rohit507/exam_gen

theme:
  name: material
  custom_dir : docs/theme/
  palette:
    scheme: slate
    primary: blue
    secondary: yellow
  icon:
    repo: check-square

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Miscellaneous Notes: misc-notes.md
  - Developer API:
      - Mixins:
          - PrepareAttrs: api/mixins/prepare_attrs.md 

plugins:
  - search
  - localsearch
  - mkdocstrings:
      watch:
        - exam_gen/ 

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true

use_directory_urls: false
