site_name: UCB EECS Exam Generator

repo_name: rohit507/exam_gen

theme:
  name: material
  custom_dir : docs/theme/
  palette:
    scheme: slate
    primary: blue
    secondary: yellow
  icon:
    repo: check-square

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Miscellaneous Notes: misc-notes.md
  - Developer API:
      - exam_gen.mixins:
          - settings: api/mixins/settings.md
          - config: api/mixins/config.md
          - prepare_attrs: api/mixins/prepare_attrs.md
          - yaml_rep: api/mixins/yaml_rep.md
          - template: api/mixins/template.md
      - exam_gen.util:
          - dynamic_call: api/util/dynamic_call.md
          - error: api/util/error.md
          - logging: api/util/logging.md

plugins:
  - search
  - localsearch
  - mkdocstrings:
      watch:
        - exam_gen/

markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - toc:
      permalink: true

use_directory_urls: false
